name: pinact
description: Pin GitHub Actions and reusable workflows by pinact
author: Shunsuke Suzuki
branding:
  icon: git-commit
  color: blue
inputs:
  github_token:
    description: |
      GitHub Access Token
      contents:write - Push commits
    required: false
  app_id:
    description: |
      GitHub App ID
    required: false
  app_private_key:
    description: |
      GitHub App Private Key
    required: false
  skip_push:
    required: false
    description: |
      Skip pushing a commit
    default: "false"
runs:
  using: composite
  steps:
    # Install pinact by aqua
    - shell: bash
      id: pinact_installed
      run: |
        if command -v pinact; then
          echo "value=true" >> "$GITHUB_OUTPUT"
          exit 0
        fi
        echo "value=false" >> "$GITHUB_OUTPUT"

    - run: echo "value=$GITHUB_ACTION_PATH/aqua/aqua.yaml" >> "$GITHUB_OUTPUT"
      id: aqua_config
      if: steps.pinact_installed.outputs.value == 'false'
      shell: bash
    - uses: aquaproj/aqua-installer@e2d0136abcf70b7a2f6f505720640750557c4b33 # v3.1.1
      if: steps.pinact_installed.outputs.value == 'false'
      with:
        aqua_version: v2.45.1
        skip_install_aqua: "true"
      env:
        AQUA_CONFIG: ${{steps.aqua_config.outputs.value}}

    - shell: bash
      run: pinact -v
      env:
        AQUA_GLOBAL_CONFIG: ${{env.AQUA_GLOBAL_CONFIG}}:${{steps.aqua_config.outputs.value}}
    - shell: bash
      id: files
      run: |
        tempfile=$(mktemp)
        git ls-files | grep -E '\.github/workflows/[^/]+\.ya?ml$' > "$tempfile"
        git ls-files | grep -E '^(.*/)?action\.ya?ml?' >> "$tempfile" || true
        {
          echo 'value<<EOF'
          cat "$tempfile"
          echo EOF
        } >> "$GITHUB_OUTPUT"

    - shell: bash
      run: |
        set -euo pipefail
        if echo "$FILES" | ! xargs -r pinact run --check; then
          echo "::error:: GitHub Actions aren't pinned."
          exit 1
        fi
      if: fromJSON(inputs.skip_push)
      env:
        FILES: ${{ steps.files.outputs.value }}
        AQUA_GLOBAL_CONFIG: ${{env.AQUA_GLOBAL_CONFIG}}:${{steps.aqua_config.outputs.value}}

    - shell: bash
      run: echo "$FILES" | xargs -r pinact run
      if: |
        ! fromJSON(inputs.skip_push)
      env:
        FILES: ${{ steps.files.outputs.value }}
        AQUA_GLOBAL_CONFIG: ${{env.AQUA_GLOBAL_CONFIG}}:${{steps.aqua_config.outputs.value}}

    - shell: bash
      id: check_changed
      if: |
        ! fromJSON(inputs.skip_push) && steps.check_changed.outputs.value == 'true'
      env:
        FILES: ${{ steps.files.outputs.value }}
      run: |
        set -euo pipefail
        if echo "$FILES" | xargs -r git diff --exit-code; then
          echo "::notice:: No changes" >&2
          echo "value=false" >> "$GITHUB_OUTPUT"
        else
          echo "value=true" >> "$GITHUB_OUTPUT"
        fi

    - shell: bash
      if: |
        ! fromJSON(inputs.skip_push) && steps.check_changed.outputs.value == 'true'
      run: |
        echo "::error:: GitHub Actions aren't pinned. A commit is pushed automatically to pin GitHub Actions."

    - uses: suzuki-shunsuke/commit-action@9faad521ea6a1e768439ffbe6b25b6cb3fc1b181 # v0.0.6
      if: |
        ! fromJSON(inputs.skip_push) && steps.check_changed.outputs.value == 'true'
      with:
        files: ${{ steps.files.outputs.value }}
        github_token: ${{inputs.github_token}}
        app_id: ${{inputs.app_id}}
        app_private_key: ${{inputs.app_private_key}}
        commit_message: "chore(pinact): pin GitHub Actions"
