name: pinact
description: Pin GitHub Actions and reusable workflows by pinact
author: Shunsuke Suzuki
branding:
  icon: git-commit
  color: blue
inputs:
  default_github_token:
    description: |
      GitHub Access Token
      contents:write - Push commits
    required: false
    default: ${{github.token}}
  github_token:
    description: |
      GitHub Access Token
      contents:write - Push commits
    required: false
  app_id:
    description: |
      GitHub App ID
    required: false
  app_private_key:
    description: |
      GitHub App Private Key
    required: false
  skip_push:
    required: false
    description: |
      Skip pushing a commit
    default: "false"
  update:
    required: false
    description: |
      pinact run's --update option
    default: "false"
  min_age:
    required: false
    description: |
      pinact run's --min-age option
  verify:
    required: false
    description: |
      pinact run's --verify option
  includes:
    required: false
    description: |
      pinact run's --include option.
      Each value is newline separated.
      Lines starting with # are ignored.
runs:
  using: node20
  main: dist/index.js
